### ISSUE TITLE
Crash with Late Company

### ISSUE THREAD

**Issue by 400Ferrets** [PopleZoo/BetterItemScan#1]
not much more to it, when using the latest [Late Company](https://thunderstore.io/c/lethal-company/p/anormaltwig/LateCompany/) with the latest BetterItemScan the game will often crash when a new player joins the lobby outside of when you would normally be able to in vanilla. (Note, this is server side. the host crashes with this mod combo, even if the client is playing fully vanilla)

**Comment by PopleZoo** [comment]
Hi, thanks for posting and bringing this issue to my attention. Without the error message there isn't much I can do. Please can u share the error message if or when it happens again. Thanks in advance!

**Comment by 400Ferrets** [comment]
[Player.log](https://github.com/PopleZoo/BetterItemScan/files/13725136/Player.log)
Here is the log, you should find the most recent server closing (end of file) has the error(s) somewhere near the most recent join preceding it. I have redacted all SteamIDs in this file, let me know if it contains anything else sensitive. I have narrowed down the crash to be BetterItemScan's interaction with LateCompany with confidence (just these two is all you need (and beepin)), good luck  :p 
note: this specific log does have other mods loaded
note note: this is extremely reproducible, I can make more logs if you like, but it does not crash on every new client join

**Comment by PopleZoo** [comment]
Sorry for the long break, does this issue still persist even after the updates?

**Comment by qwertzuiii** [comment]
I got no crashes with this mod combo.
