### ISSUE TITLE
Way to disable "Scan Initiated!" or show it when necessary

### ISSUE THREAD

**Issue by allanjales** [PopleZoo/BetterItemScan#11]
I am using the [Hold Scan Button mod](https://thunderstore.io/c/lethal-company/p/FutureSavior/Hold_Scan_Button/) which allows to constantly call scan function on game. Even with UI cooldown about 3 seconds, while I am hold scan button, I get spammed "Scan initiated!" on terminal even when it does not update my UI. It is also known that logging messages is a FPS drop causes. I lose about 10 FPS while I am scanning.

So, where is what I am asking for:

- option to disable "Scan Initiated!" message
- or just show it when it can and will change UI information (**better solution**).

As I saw, it is a problem [from this line](https://github.com/PopleZoo/BetterItemScan/blob/7c168f22cd2db9b765f8974f15759f6dff91cf1c/BetterItemScan%20-%20Code%20behind%20the%20scenes/Patches/HudManagerPatch_UI.cs#L102)

**Comment by PopleZoo** [comment]
This issue should be fixed with the new update. The update reworked areas of the code where methods where called multiple times where they should. Thanks
