### ISSUE TITLE
[Suggestion] Toggleable UI Features

### ISSUE THREAD

**Issue by Avemado** [PopleZoo/BetterItemScan#2]
Scanning a lot of items at once really clutters up your screen with them all being listed at once.
Would be nice to have different configs for items being listed and the total value currently on ship, so you can disable the items being listed on the HUD.

**Comment by PopleZoo** [comment]
Thanks for your feedback, there are already config options for showing the total scrap values of items on the ship as well as the showing the ships total haul. However I do agree the UI does cover a lot of the screen, so I will add more UI adjustments.
