### ISSUE TITLE
scanning issue

### ISSUE THREAD

**Issue by Dragongas2003** [PopleZoo/BetterItemScan#3]
when scanning an item the color for the scanned item keeps geting a # added onto it causeing this to happen

![Screenshot 2023-12-14 130056](https://github.com/PopleZoo/BetterItemScan/assets/153855526/7cf2c377-847c-4753-bda3-087a1fbe4564)

I originally thought this was an issue with the newer version but when going back a version it was still having this issue.

this is a huge modpack so it could be a incompatibility issue but i dont seem to see a error in the output log that suggests the mod in particular is having an issue 

[LogOutput.log](https://github.com/PopleZoo/BetterItemScan/files/13718901/LogOutput.log)

**Comment by PopleZoo** [comment]
Can u tell me which version it is? I can't tell from log because of thunderstore rounds down the last digit. If this is version 2.1.4, there is a hotfix out so u should definitely update. Thanks for ur feedback!

**Comment by Dragongas2003** [comment]
heres a video showing the version is the latest and the setting is correct but in game it breaks with every scan adding another # 
https://github.com/PopleZoo/BetterItemScan/assets/153855526/1830ecf9-129c-4f94-bbdc-fb0624d15646
here is the log file for this test as well
[LogOutput.log](https://github.com/PopleZoo/BetterItemScan/files/13720192/LogOutput.log)

**Comment by Dragongas2003** [comment]
also noted that this is the config after the video 
![image](https://github.com/PopleZoo/BetterItemScan/assets/153855526/8a37357f-d125-4496-8c32-0a5e86aabb22)

**Comment by PopleZoo** [comment]
ok, it seems like u not using the newest version, 2.1.5.
