### ISSUE TITLE
Invalid colour

### ISSUE THREAD

**Issue by YoBii** [PopleZoo/BetterItemScan#5]
Getting this error for every scanned item. Using default config

Console output
> [Error  : Unity Log] #78FFAE is an invalid colour. Please remember the'#'
[Error  : Unity Log] #78FFAE is an invalid colour. Please remember the'#'
[Error  : Unity Log] #78FFAE is an invalid colour. Please remember the'#'
[Error  : Unity Log] #78FFAE is an invalid colour. Please remember the'#'
[Error  : Unity Log] #78FFAE is an invalid colour. Please remember the'#'

Config
> \#\# The default text color for items that have been scanned, value must be a hexadecimal
> \# Setting type: String
> \# Default value: #78FFAE
> ItemTextColorHex = #78FFAE

**Comment by PopleZoo** [comment]
Sorry for no replying sooner hopefully the updates that were released after your message solved your issue. If not please sent feedback
