### ISSUE TITLE
Unable to see the total of scanned items

### ISSUE THREAD

**Issue by strudel-s** [PopleZoo/BetterItemScan#6]
When scanning objects, I cannot see the total $ of scanned items at all. I think this might be an issue with my resolution being 3440x1440, as I notice some things tend to get cut off in the pause menu.

**Comment by PopleZoo** [comment]
There are config options that allow you to alter the UI for your monitor, just try out what values work for you

**Comment by strudel-s** [comment]
Ended up fixing it with the LCUltrawide mod, but thank you regardless.Sent from my iPhoneOn Jan 20, 2024, at 10:00 PM, Bailley ***@***.***> wrote:﻿
There are config options that allow you to alter the UI for your monitor, just try out what values work for you
