### ISSUE TITLE
Incompatible with GeneralImprovements

### ISSUE THREAD

**Issue by darkbrewery** [PopleZoo/BetterItemScan#7]
See this issue:  https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/issues/26

**Comment by PopleZoo** [comment]
Hi, sorry for not replying sooner. Generalimprovements and betteritemscan deal with the some of the same functions, as betteritemscan alters them heavily compared to generalimprovements this conflict cannot be helped
