### ISSUE TITLE
[SUGGESTION] Add overtime bonus calculation to the scan

### ISSUE THREAD

**Issue by Nyxlanders** [PopleZoo/BetterItemScan#9]
One thing that most players suffer is about having to calculate the overtime bonus in their head. But the calculation is simple to do, but having to manually do that every round is a pain in the *** (even more if you play solo). 

Math formula:
`(ScrapSold - Quota) / 5`

I think you can do a estimated overtime value based on how many scrap you can sell in the present time. 
Name ideas: "Rough Overtime" or "Estimated Overtime".

Reference: https://www.youtube.com/shorts/hUpmR3inZLI

**Comment by PopleZoo** [comment]
In future please either dm me or message in the lethal company discord(s) betteritemscan thread. Or you can message in the mod ideas channel as well. Thanks for the suggestion anyhow
